# Generated by Django 4.2.23 on 2025-07-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinput", old_name="message", new_name="favorite_colors",
        ),
        migrations.RemoveField(model_name="userinput", name="email",),
    ]
