# Generated by Django 4.2.23 on 2025-07-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0002_rename_message_userinput_favorite_colors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinput", old_name="favorite_colors", new_name="variables",
        ),
    ]
