# Generated by Django 4.2.23 on 2025-07-31 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0003_rename_favorite_colors_userinput_variables"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinput", name="variables",),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_name", models.CharField(max_length=200)),
                (
                    "standard_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="formapp.userinput",
                    ),
                ),
            ],
        ),
    ]
