# Generated by Django 4.2.23 on 2025-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0004_remove_userinput_variables_variable"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="column_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="variable",
            name="units",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
