# Generated by Django 4.2.23 on 2025-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0005_variable_column_number_variable_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata_type",
                    models.CharField(
                        choices=[
                            ("coordinate_variable", "Coordinate variable"),
                            ("comment", "Comment"),
                            ("start_time", "Start time"),
                            ("end_time", "End time"),
                            ("rights", "Rights"),
                            ("last_revised_date", "Last revised date"),
                            ("history", "History"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata_value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Creators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("contributor", "Contributor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("column_number", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "additional_info",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.RemoveField(model_name="variable", name="user_input",),
        migrations.AlterField(
            model_name="variable",
            name="column_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="variable", name="units", field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(name="UserInput",),
    ]
