# Generated by Django 4.2.23 on 2025-08-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0006_additionalmetadata_creators_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creators",
            old_name="additional_info",
            new_name="additional_creator_info",
        ),
    ]
