# Generated by Django 4.2.23 on 2025-08-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0007_rename_additional_info_creators_additional_creator_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("contributor", "Contributor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("column_number", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "additional_creator_info",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(name="Creators",),
        migrations.AddField(
            model_name="creator",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creators",
                to="formapp.submission",
            ),
        ),
        migrations.AddField(
            model_name="additionalmetadata",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="formapp.submission",
            ),
        ),
        migrations.AddField(
            model_name="variable",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="formapp.submission",
            ),
        ),
    ]
