# Generated by Django 4.2.23 on 2025-08-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0009_submission_dataset_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creator",
            old_name="column_number",
            new_name="person_column_number",
        ),
        migrations.AddField(
            model_name="additionalmetadata",
            name="metadata_column_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
